/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw3(PApplet appc, GWinData data) { //_CODE_:window1:631852:
  appc.background(230);
} //_CODE_:window1:631852:

public void playSong(GButton source, GEvent event) { //_CODE_:playButton:297852:
  if (playSong == false) { // curr not playing, play
    playSong = true;
  } else if (playSong == true) { // curr playing, pause
    playSong = false;
    sinTrack.stopTrack("sin");
    triTrack.stopTrack("tri");
    sqrTrack.stopTrack("sqr");
    sawTrack.stopTrack("saw");
  }
} //_CODE_:playButton:297852:

public void stopSong(GButton source, GEvent event) { //_CODE_:stopButton:695609:
  playSong = false;
  sinTrack.stopTrack("sin");
  triTrack.stopTrack("tri");
  sqrTrack.stopTrack("sqr");
  sawTrack.stopTrack("saw");
  beat = 0;
} //_CODE_:stopButton:695609:

public void importFile(GButton source, GEvent event) { //_CODE_:importButton:385551:
  println("importButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:importButton:385551:

public void exportFile(GButton source, GEvent event) { //_CODE_:exportButton:839331:
  println("exportButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:exportButton:839331:

public void createNote(GButton source, GEvent event) { //_CODE_:createNoteButton:890698:
  println("createNoteButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:createNoteButton:890698:

public void deleteNote(GButton source, GEvent event) { //_CODE_:deleteNoteButton:866397:
  println("deleteNoteButton - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:deleteNoteButton:866397:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 250, 320, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw3");
  playButton = new GButton(window1, 10, 130, 110, 30);
  playButton.setText("PLAY/PAUSE");
  playButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  playButton.addEventHandler(this, "playSong");
  stopButton = new GButton(window1, 130, 130, 110, 30);
  stopButton.setText("STOP");
  stopButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  stopButton.addEventHandler(this, "stopSong");
  musicControls = new GLabel(window1, 80, 100, 90, 20);
  musicControls.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  musicControls.setText("Music Controls");
  musicControls.setOpaque(false);
  importButton = new GButton(window1, 10, 40, 110, 30);
  importButton.setText("Import .lamb");
  importButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  importButton.addEventHandler(this, "importFile");
  projectManagement = new GLabel(window1, 60, 10, 130, 20);
  projectManagement.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  projectManagement.setText("Project Management");
  projectManagement.setOpaque(false);
  exportButton = new GButton(window1, 130, 40, 110, 30);
  exportButton.setText("Export .lamb");
  exportButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  exportButton.addEventHandler(this, "exportFile");
  musicCreation = new GLabel(window1, 80, 190, 90, 20);
  musicCreation.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  musicCreation.setText("Music Creation");
  musicCreation.setOpaque(false);
  createNoteButton = new GButton(window1, 10, 220, 110, 30);
  createNoteButton.setText("Create Note");
  createNoteButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  createNoteButton.addEventHandler(this, "createNote");
  deleteNoteButton = new GButton(window1, 130, 220, 110, 30);
  deleteNoteButton.setText("Delete Note");
  deleteNoteButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  deleteNoteButton.addEventHandler(this, "deleteNote");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton playButton; 
GButton stopButton; 
GLabel musicControls; 
GButton importButton; 
GLabel projectManagement; 
GButton exportButton; 
GLabel musicCreation; 
GButton createNoteButton; 
GButton deleteNoteButton; 
