/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw3(PApplet appc, GWinData data) { //_CODE_:window1:631852:
  appc.background(230);
} //_CODE_:window1:631852:

public void playSong(GButton source, GEvent event) { //_CODE_:playButton:297852:
  if (playSong == false) { // curr not playing, play
    playSong = true;
  } else { // curr playing, pause
    playSong = false;
    sinTrack.stopTrack("sin");
    triTrack.stopTrack("tri");
    sqrTrack.stopTrack("sqr");
    sawTrack.stopTrack("saw");
  }
} //_CODE_:playButton:297852:

public void stopSong(GButton source, GEvent event) { //_CODE_:stopButton:695609:
  playSong = false;
  sinTrack.stopTrack("sin");
  triTrack.stopTrack("tri");
  sqrTrack.stopTrack("sqr");
  sawTrack.stopTrack("saw");
  currSin = 0;
  currTri = 0;
  currSqr = 0;
  currSaw = 0;
  beat = 0;
} //_CODE_:stopButton:695609:

public void importFile(GButton source, GEvent event) { //_CODE_:importButton:385551:
  sinTrack.samples.clear();
  triTrack.samples.clear();
  sqrTrack.samples.clear();
  sawTrack.samples.clear();
  
  selectInput("Select .lamb file", "importProject", new File(sketchPath() + "/"));
  
} //_CODE_:importButton:385551:

public void showSin(GButton source, GEvent event) { //_CODE_:showSinButton:890698:
  showSin = !showSin;
} //_CODE_:showSinButton:890698:

public void showTri(GButton source, GEvent event) { //_CODE_:showTriButton:866397:
  showTri = !showTri;
} //_CODE_:showTriButton:866397:

public void showSqr(GButton source, GEvent event) { //_CODE_:showSqrButton:342927:
  showSqr = !showSqr;
} //_CODE_:showSqrButton:342927:

public void showSaw(GButton source, GEvent event) { //_CODE_:showSawButton:464865:
  showSaw = !showSaw;
} //_CODE_:showSawButton:464865:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 250, 320, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw3");
  playButton = new GButton(window1, 10, 130, 110, 30);
  playButton.setText("PLAY/PAUSE");
  playButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  playButton.addEventHandler(this, "playSong");
  stopButton = new GButton(window1, 130, 130, 110, 30);
  stopButton.setText("STOP");
  stopButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  stopButton.addEventHandler(this, "stopSong");
  musicControls = new GLabel(window1, 80, 100, 90, 20);
  musicControls.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  musicControls.setText("Music Controls");
  musicControls.setOpaque(false);
  importButton = new GButton(window1, 10, 40, 230, 30);
  importButton.setText("Import .lamb");
  importButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  importButton.addEventHandler(this, "importFile");
  projectManagement = new GLabel(window1, 60, 10, 130, 20);
  projectManagement.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  projectManagement.setText("Project Management");
  projectManagement.setOpaque(false);
  musicCreation = new GLabel(window1, 80, 190, 90, 20);
  musicCreation.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  musicCreation.setText("Music Creation");
  musicCreation.setOpaque(false);
  showSinButton = new GButton(window1, 10, 220, 110, 30);
  showSinButton.setText("show/hide SIN");
  showSinButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  showSinButton.addEventHandler(this, "showSin");
  showTriButton = new GButton(window1, 130, 220, 110, 30);
  showTriButton.setText("show/hide TRI");
  showTriButton.addEventHandler(this, "showTri");
  showSqrButton = new GButton(window1, 10, 260, 110, 30);
  showSqrButton.setText("show/hide SQR");
  showSqrButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  showSqrButton.addEventHandler(this, "showSqr");
  showSawButton = new GButton(window1, 130, 260, 110, 30);
  showSawButton.setText("show/hide SAW");
  showSawButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  showSawButton.addEventHandler(this, "showSaw");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GButton playButton; 
GButton stopButton; 
GLabel musicControls; 
GButton importButton; 
GLabel projectManagement; 
GLabel musicCreation; 
GButton showSinButton; 
GButton showTriButton; 
GButton showSqrButton; 
GButton showSawButton; 
